name: sass_transformer
version: 0.5.0
description: >
  Sass-transformer for pub-serve and pub-build.
authors:
  - Luis Vargas <luisvargastijerino@gmail.com>
homepage: https://github.com/dart-league/sass_transformer
dependencies:
  barback: ^0.15.0
  utf: ^0.9.0
dev_dependencies:
  test: ^0.12.0
  mock: ^0.12.0
